# Generated by Django 5.1.1 on 2024-10-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Signup',
        ),
    ]
