# Generated by Django 5.1.1 on 2024-10-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_login_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hgstypes', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
